apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafkarestservice
  name: kafkarestservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkarestservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafkarestservice
    spec:
      containers:
      - image: restservice:0.0.1-SNAPSHOT
        imagePullPolicy: Never
        name: restservice
        resources: {}
status: {}
---
# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: null
#   labels:
#     app: kafkarestservice
#   name: kafkarestservice
# spec:
#   ports:
#   - name: 8080-8080
#     port: 8080
#     protocol: TCP
#     targetPort: 8080
#     nodePort: 30080
#   selector:
#     app: kafkarestservice
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafkarestservice
  name: kafkarestservice
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kafkarestservice
  type: ClusterIP
status:
  loadBalancer: {}
