apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafkarestservice
  name: kafkarestservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkarestservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafkarestservice
    spec:
      containers:
      - image: kafka-ms:0.0.1
        imagePullPolicy: Never
        name: kafkarestservice
        resources: {}
        ports:
          - containerPort: 8084
            name: kafkaservport
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafkarestservice
spec:
  type: NodePort
  selector:
    app: kafkarestservice
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: kafkaservport
