spring:
   kafka:
      bootstrap-servers: kafkaservice:9092,kafka-svc-external:30080,kafka-svc-external:9093
      producer:
         acks: all
         key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
         value-serializer: org.apache.kafka.common.serialization.StringSerializer
test:
  topic: embedded-test-topic
server:
   port : 8084