spring:
   kafka:
      bootstrap-servers: localhost:30080,172.17.0.5:9092
      producer:
         acks: all
         key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
         value-serializer: org.apache.kafka.common.serialization.StringSerializer
test:
  topic: embedded-test-topic