apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kube-demo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zookeeper
            - name: ALLOW_ANONYMOUS_LOGIN
              value: 'yes'
            - name: ZOOKEEPER_CLIENT_PORT
              value: '2181'
          name: zookeeper
          image: gacr2nsandbox.azurecr.io/confluentinc/cp-zookeeper:7.1.0
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
          volumeMounts:
            - name: etc-kafka
              mountPath: /etc/kafka
            - name: var-log-kafka
              mountPath: /var/log/kafka
          ports:
            - containerPort: 2181
      volumes:
        - name: etc-kafka
          emptyDir: {}
        - name: var-log-kafka
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kube-demo-test
  labels:
    name: zookeeper
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    name: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaservice
  namespace: kube-demo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafkaservice
  template:
    metadata:
      labels:
        name: kafkaservice
    spec:
      hostname: kafkaservice
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://kafkaservice:9092,EXTERNAL://localhost:30080
            - name: KAFKA_LISTENERS
              value: INTERNAL://:9092,EXTERNAL://:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          name: kafkaservice
          image: gacr2nsandbox.azurecr.io/confluentinc/cp-kafka:7.1.0
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
          volumeMounts:
            - name: etc-kafka
              mountPath: /etc/kafka
            - name: var-log-kafka
              mountPath: /var/log/kafka
          ports:
            - name: port9092
              containerPort: 9092
            - name: port9093
              containerPort: 9093
      volumes:
        - name: etc-kafka
          emptyDir: {}
        - name: var-log-kafka
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafkaservice
  namespace: kube-demo-test
  labels:
    name: kafkaservice
spec:
  ports:
    - name: port9092
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    name: kafkaservice
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc-external
  namespace: kube-demo-test
  labels:
    app: kafka-svc-external
spec:
  selector:
    name: kafkaservice
  ports:
    - name: port9093
      port: 9093
      protocol: TCP
      nodePort: 30080
  type: NodePort